# Generated by Django 3.2.25 on 2024-11-22 17:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20241122_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
