name: Checks
on: [push, workflow_dispatch]
jobs:
    test-lint:
        name: Test and List
        runs-on: ubuntu-latest
        steps:
            - name: Login to docker hub
              uses: docker/login-action@v1
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install Docker Compose
              run: |
                DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)
                sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose
                # Verify the installation
                docker-compose --version
            
            - name: Test
              run: docker-compose run --rm app sh -c "python manage.py test"
            - name: Lint
              run: docker-compose run --rm app sh -c "flake8"
